apiVersion: v1
kind: Pod
metadata:
  name: test-bad-limit-over
spec:
  containers:
    - name: mini-git
      image: idock.daumkakao.io/uzu_ina/mini-git-m2
      resources:
        limits:
          cpu: "500m"
          memory: "500m"