apiVersion: v1
kind: Pod
metadata:
  name: idock-test
spec:
  containers:
    - name: opa
      image: idock.daumkakao.io/uzu_ina/mini-git-m2
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"