apiVersion: v1
kind: Pod
metadata:
  name: idock-bad-test-not-allowed-regs
spec:
  containers:
    - name: wrong-image
      image: gcr.io/smythe-kpc/testbuilds/opa:0.9.2
      args:
        - "run"
        - "--server"
        - "--addr=localhost:8080"
      resources:
        limits:
          cpu: "100m"
          memory: "30Mi"